name: Build macOS

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'LICENSE'
      - '**/.gitignore'
      - '**/.README.md'
      - '.github/assets/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'LICENSE'
      - '**/.gitignore'
      - '**/.README.md'
      - '.github/assets/**'
      - '.github/ISSUE_TEMPLATE/**'

  workflow_dispatch:
    inputs:
      artifact_upload:
        description: 'Artifact uploading'
        required: false
        type: boolean

env:
  ENV_EXAMPLE_FILE: .env.example
  PACKAGE_FILE: package.json
  OUT_DIR: out

jobs:
  release:
    permissions: write-all
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13]
        node-version: [14.x]

    env:
      ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
      ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder
      PYTHON: python3.10
      NODE_GYP_FORCE_PYTHON: python3.10

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install jq
        run: brew install jq
      - name: Check jq version
        run: jq --version

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Electron
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/.cache/electron
          key: ${{ runner.os }}-electron-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      - name: Cache Electron-Builder
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/.cache/electron-builder
          key: ${{ runner.os }}-electron-builder-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-electron-builder-cache-

      - name: Remove other python
        run: sudo rm -rf /System/Library/Frameworks/Python.framework/

      - name: Install python@3.10
        run: brew install python@3.10

      - name: Load variables into the .env file
        shell: bash
        run: |
          source ${{env.ENV_EXAMPLE_FILE}}

          SENTRY_DSN="${{ secrets.SENTRY_DSN }}"
          YANDEX_TRACKING_ID="${{ secrets.YANDEX_TRACKING_ID }}"
          ADS_URLS="${{ secrets.ADS_URLS }}"
          
          echo "SENTRY_DSN=$SENTRY_DSN" >> .env
          echo "YANDEX_TRACKING_ID=$YANDEX_TRACKING_ID" >> .env
          echo "ADS_URLS=$ADS_URLS" >> .env
          echo "VK_APP_ID=$VK_APP_ID" >> .env
          echo "API_ENDPOINT_URL=$API_ENDPOINT_URL" >> .env
          echo "STATIC_ENDPOINT_URL=$STATIC_ENDPOINT_URL" >> .env
          echo "EXT_API_SERVER=$EXT_API_SERVER" >> .env
          echo "DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID" >> .env
          echo "APP_UPDATE_CHANNEL_ENDPOINT_URL=$APP_UPDATE_CHANNEL_ENDPOINT_URL" >> .env
      
      - name: Get the application version from the "package.json" file
        shell: bash
        run: echo "APP_VERSION=$(cat ${{env.PACKAGE_FILE}} | jq -r '.version')" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn

      - name: Run build
        shell: bash
        run: |
          sudo chmod +x build.sh
          ./build.sh

      - name: Upload artifact
        if: ${{ inputs.artifact_upload == true || startsWith(github.ref, 'refs/heads/main')}}
        uses: actions/upload-artifact@v3
        with:
          name: Anilibrix Plus
          path: ${{env.OUT_DIR}}/*.dmg


      - name: Create Release
        if: ${{ startsWith(github.ref, 'refs/heads/main') }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{env.APP_VERSION}}
          files: ${{env.OUT_DIR}}/*.dmg