name: Build for web and publish to gh-pages

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-18.04

    env:
      ADS_URLS: ${{ secrets.ADS_URLS }}
      VK_APP_ID: ${{ secrets.VK_APP_ID }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      API_ENDPOINT_URL: ${{ secrets.API_ENDPOINT_URL }}
      YANDEX_TRACKING_ID: ${{ secrets.YANDEX_TRACKING_ID }}
      STATIC_ENDPOINT_URL: ${{ secrets.STATIC_ENDPOINT_URL }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.0
        with:
          node-version: '12.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: 'yarn install'
      - run: 'yarn web:build'

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
